### ISSUE TITLE
Passing environment variables to the workflow

### ISSUE THREAD

**Issue by ThomasRichtsfeld** [touchlab/KMMBridgeGithubWorkflow#10]
I am not sure if this is a real issue or if I lack some GHA experience. 
I have the following workflow

```
name: iOS Publish
on:
  pull_request:
  workflow_dispatch:

#  push:
#    branches:
#      - "main"

env:
  gitHubUserName: ${{ secrets.GH_USER_NAME }}
  gitHubAccessToken: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  publishIOS:
    name: Publish iOS
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildautoversion.yml@v1.0
    with:
      jvmVersion: 17
      runsOn: ubuntu-20.04
      versionBaseProperty: LIBRARY_VERSION
```

The KKMBridge workflow launches a gradle task under the hood that executes some code in my underlying gradle configuration in the Android project. This project needs some env variables set by the GHA. In that case `gitHubUserName` and `gitHubUserName`.
Unfortunately, when setting the `env` variables in this workflow it seems to be not propagated down to the KMMBridge workflow. `gitHubUserName` and `gitHubUserName` are always null when the underlying gradle tasks in the Android project are executed.

Who has an idea of a potential fix?

**Comment by timionius** [comment]
The same here. Looks like GitHub workflows doesn't allow to pass env variables into reusable flows - [link](https://github.com/orgs/community/discussions/26671)
I was able to manage it using gradle_params within the handling these parameters in settings.gradle.kts like:
workflow.yml
```
name: iOS Publish
on:
  workflow_dispatch:
    secrets:
      gradle_params:
        required: true
...
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildautoversion.yml@v1.1
    with:
      jvmVersion: 17
      versionBaseProperty: LIBRARY_VERSION
    secrets:
      gradle_params: -PGIT_USER=${{ secrets.GIT_REPOS_ACCESS_USER}} -PGIT_USER_TOKEN=${{ secrets.GIT_REPOS_ACCESS_USER_TOKEN }}
```

settings.gradle.kts
```
    props["gpr.user"] = extra["GIT_USER"]
    props["gpr.key"] = extra["GIT_USER_TOKEN"]
```

Don't forget to put Repository secrets in the git repo where you run kmpbridge
