### ISSUE TITLE
Add ability to set custom netrc credentials

### ISSUE THREAD

**Issue by russhwolf** [touchlab/KMMBridgeGithubWorkflow#2]
Right now, our docs on Artifactory recommend setting up a custom github action rather than using this one, because different netrc credentials are needed. This will also come up for other backends. We should add the ability to pass credentials manually so the workflows in this repo are usable in more non-github scenarios.

Kevin update:

Updated the workflow to take netrc params. the netrc params are optional. If none are provided, the workflow assumes the GitHub Packages config.

Params:

* inputs.netrcMachine
* secrets.netrcUsername
* secrets.netrcPassword

Make sure to set workflow to `v0.7`.

Example:

```yaml
name: KMM Bridge/iOS Publish
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"
jobs:
  call-kmmbridge-publish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.7
    with:
      netrcMachine: maven.pkg.github.com # <- Put machine here
    secrets:
      netrcUsername: kpgalligan # <- username
      netrcPassword: ghp_ASRTASRTARSTARSTARST # <- password, PAT for GitHub
      PODSPEC_SSH_KEY: ${{ secrets.PODSPEC_SSH_KEY }}
```

This has been only been tried with the same server that will work by default, `maven.pkg.github.com`. It should be tested with other servers like Artifactory.

Also need to add docs for passing in workflow params, and maybe an integration workflow.
